### PR TITLE
Added useful examples section (english and spanish)

### PR DESCRIPTION
**Pull request by Saul-BT**

### CODE REVIEW

**Comment by imba-tjd** [comment]
Validating Email and HTML are complicated. You'd better add a warning that they are not used for real validation.

**Comment by Saul-BT** [comment]
Yep, @imba-tjd you're right, I will add the warning soon.
Thanks for your feedback :smiley:

**Comment by ziishaned** [comment]
Thanks for the contribution but we will not add examples as you could find tons of examples regarding regex online. :)

**Comment by ziishaned** [comment]
#114

**Pull request closed without merging**
